name: gazebo
channels:
  - conda-forge
  - defaults
dependencies:
  - psutil
  - openpyxl
  - scipy
  - python=3.7
  - pandas
  - numpy
  - protobuf
  - matplotlib
  - pip
  - pip:
    - numba
    - gym
    - nest_asyncio