name: gazebo
channels:
  - conda-forge
  - defaults
dependencies:
  - psutil
  - openpyxl
  - scipy
  - python=3.9
  - pandas
  - numpy
  - numba
  - protobuf
  - matplotlib
  - pip
  - pip:
    - gym
    - nest_asyncio
    - tqdm
    - pymavlink==2.4.29
    - git+https://github.com/hazrmard/py3gazebo.git
    - prog_models
