# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector8d.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vector8d.proto',
  package='tarotPB.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x0evector8d.proto\x12\x0ctarotPB.msgs\"\x92\x01\n\x08Vector8d\x12\x0f\n\x07motor_1\x18\x01 \x02(\x01\x12\x0f\n\x07motor_2\x18\x02 \x02(\x01\x12\x0f\n\x07motor_3\x18\x03 \x02(\x01\x12\x0f\n\x07motor_4\x18\x04 \x02(\x01\x12\x0f\n\x07motor_5\x18\x05 \x02(\x01\x12\x0f\n\x07motor_6\x18\x06 \x02(\x01\x12\x0f\n\x07motor_7\x18\x07 \x02(\x01\x12\x0f\n\x07motor_8\x18\x08 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VECTOR8D = _descriptor.Descriptor(
  name='Vector8d',
  full_name='tarotPB.msgs.Vector8d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor_1', full_name='tarotPB.msgs.Vector8d.motor_1', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_2', full_name='tarotPB.msgs.Vector8d.motor_2', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_3', full_name='tarotPB.msgs.Vector8d.motor_3', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_4', full_name='tarotPB.msgs.Vector8d.motor_4', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_5', full_name='tarotPB.msgs.Vector8d.motor_5', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_6', full_name='tarotPB.msgs.Vector8d.motor_6', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_7', full_name='tarotPB.msgs.Vector8d.motor_7', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_8', full_name='tarotPB.msgs.Vector8d.motor_8', index=7,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=179,
)

DESCRIPTOR.message_types_by_name['Vector8d'] = _VECTOR8D

Vector8d = _reflection.GeneratedProtocolMessageType('Vector8d', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR8D,
  __module__ = 'vector8d_pb2'
  # @@protoc_insertion_point(class_scope:tarotPB.msgs.Vector8d)
  ))
_sym_db.RegisterMessage(Vector8d)


# @@protoc_insertion_point(module_scope)
